# Build-Manifest.ps1 - maintainer-side tool.
# Scans a pack ROOT folder (mods\, config\, resourcepacks\, datapacks\ -
# whichever exist), uploads new/changed files as GitHub Release assets,
# and writes manifest.json that AnuDownloader.ps1 consumes.
#
# Usage:
#   .\Build-Manifest.ps1 -PackRoot "C:\...\Medieval Fantasy" -Repo "anubissxd/minecraft-servers" -Tag "medieval-fantasy-pack" -PackName "Medieval Fantasy" -Version "1.0.0"

param(
    [Parameter(Mandatory=$true)][string]$PackRoot,
    [string]$Repo = "anubissxd/minecraft-servers",
    [string]$Tag = "medieval-fantasy-pack",
    [string]$PackName = "Medieval Fantasy",
    [string]$Version = (Get-Date -Format "yyyy.MM.dd-HHmm"),
    [string]$ManifestOut = (Join-Path $PSScriptRoot "..\..\distribution\medieval-fantasy\manifest.json")
)

# Subfolders under PackRoot that get synced to players. config\ is
# intentionally excluded - those files are auto-generated by each mod on
# first launch, so shipping them adds no value and just bloats the pack.
$SyncedFolders = @("mods", "resourcepacks", "datapacks")

function Get-FileSha256($path) {
    (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLower()
}

Write-Host "Mevcut release kontrol ediliyor: $Tag"
$releaseExists = $true
gh release view $Tag --repo $Repo *> $null
if ($LASTEXITCODE -ne 0) {
    $releaseExists = $false
    Write-Host "Release yok, oluşturuluyor..."
    gh release create $Tag --repo $Repo --title "$PackName Pack Files" --notes "AnuDownloader tarafından kullanılan paket dosyaları. Elle indirmeyin." | Out-Null
}

$oldManifest = $null
if (Test-Path $ManifestOut) {
    try { $oldManifest = Get-Content $ManifestOut -Raw | ConvertFrom-Json } catch { $oldManifest = $null }
}
$oldByPath = @{}
if ($oldManifest) {
    foreach ($f in $oldManifest.files) {
        # Legacy manifests (mods-only) had no "path" field - a bare filename
        # always meant mods\<filename>.
        $p = if ($f.path) { $f.path } else { "mods/$($f.filename)" }
        $oldByPath[$p] = $f
    }
}

$scanned = @()
foreach ($sub in $SyncedFolders) {
    $subPath = Join-Path $PackRoot $sub
    if (-not (Test-Path $subPath)) { continue }
    Get-ChildItem -Path $subPath -Recurse -File | ForEach-Object {
        $relPath = $_.FullName.Substring($PackRoot.Length).TrimStart('\', '/') -replace '\\', '/'
        $scanned += [pscustomobject]@{ File = $_; RelPath = $relPath }
    }
}
Write-Host "Toplam $($scanned.Count) dosya bulundu ($($SyncedFolders -join ', ') altında)."

$newFiles = @()
$toUpload = @()

foreach ($item in $scanned) {
    $hash = Get-FileSha256 $item.File.FullName
    $existing = $oldByPath[$item.RelPath]
    if ($existing -and $existing.sha256 -eq $hash) {
        # değişmemiş, tekrar yükleme
        $newFiles += $existing
    } else {
        $toUpload += @{ item = $item; hash = $hash }
    }
}

Write-Host "$($toUpload.Count) dosya yeni/değişmiş, GitHub Release'e yüklenecek."

# GitHub release assets must have unique filenames across the WHOLE release,
# but config\ especially can have same-named files in different subfolders
# (e.g. two mods each with their own "common.toml"). Flatten the relative
# path into the asset name so collisions can't happen, while "filename" in
# the manifest stays the real leaf name AnuDownloader writes to disk.
$i = 0
foreach ($entry in $toUpload) {
    $i++
    $item = $entry.item
    $assetName = $item.RelPath -replace '/', '__'
    Write-Host "[$i/$($toUpload.Count)] Yükleniyor: $($item.RelPath)"
    # gh always uses the LOCAL filename as the remote asset name, so a
    # collision-free upload means uploading a temp copy named $assetName.
    $tmp = Join-Path ([IO.Path]::GetTempPath()) $assetName
    Copy-Item -LiteralPath $item.File.FullName -Destination $tmp -Force
    gh release upload $Tag $tmp --repo $Repo --clobber | Out-Null
    Remove-Item $tmp -Force
    $url = "https://github.com/$Repo/releases/download/$Tag/$assetName"
    $newFiles += @{
        path     = $item.RelPath
        filename = $item.File.Name
        sha256   = $entry.hash
        size     = $item.File.Length
        url      = $url
    }
}

$manifest = @{
    pack_name = $PackName
    version   = $Version
    generated = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
    files     = $newFiles
}

$manifestDir = Split-Path $ManifestOut -Parent
if (-not (Test-Path $manifestDir)) { New-Item -ItemType Directory -Path $manifestDir -Force | Out-Null }
$manifest | ConvertTo-Json -Depth 5 | Set-Content -Path $ManifestOut -Encoding UTF8

Write-Host ""
Write-Host "Manifest yazildi: $ManifestOut"
Write-Host "Toplam dosya: $($newFiles.Count)  Yeni yuklenen: $($toUpload.Count)"
Write-Host ""
Write-Host "Simdi manifest.json'u git'e commit+push etmen gerekiyor."
